AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 bucket for CI/CD artifacts (2025)'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for artifacts (must be globally unique)

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: Production
        - Key: CreatedDate
          Value: "2025-03-15"

  # Removing the bucket policy to avoid conflicts with IAM role policies
  # ArtifactBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref ArtifactBucket
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Sid: AllowSSEAlgorithmParameter
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
  #           Action: 's3:PutObject'
  #           Resource: !Sub '${ArtifactBucket.Arn}/*'
  #         - Sid: DenyUnEncryptedObjectUploads
  #           Effect: Deny
  #           Principal: '*'
  #           Action: 's3:PutObject'
  #           Resource: !Sub '${ArtifactBucket.Arn}/*'
  #           Condition:
  #             StringNotEquals:
  #               's3:x-amz-server-side-encryption': 'AES256'
  #         - Sid: DenyInsecureConnections
  #           Effect: Deny
  #           Principal: '*'
  #           Action: 's3:*'
  #           Resource: !Sub '${ArtifactBucket.Arn}/*'
  #           Condition:
  #             Bool:
  #               'aws:SecureTransport': false

Outputs:
  ArtifactBucketName:
    Description: Name of the S3 bucket for artifacts
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactBucketName

  ArtifactBucketArn:
    Description: ARN of the S3 bucket for artifacts
    Value: !GetAtt ArtifactBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactBucketArn