AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fix for S3 bucket policy to allow CodePipeline access'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for artifacts

  RoleArn:
    Type: String
    Description: ARN of the CodePipeline service role

Resources:
  UpdatedBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCodePipelineAccess
            Effect: Allow
            Principal:
              AWS: !Ref RoleArn
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketVersioning'
              - 's3:PutObject'
              - 's3:ListBucket'
            Resource:
              - !Sub 'arn:aws:s3:::${BucketName}/*'
              - !Sub 'arn:aws:s3:::${BucketName}'
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

Outputs:
  BucketPolicyUpdated:
    Description: Confirmation that the bucket policy was updated
    Value: "S3 bucket policy updated to allow CodePipeline access"