version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd WebApp
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ..
      - cp -r WebApp/build/* .
      - cp WebApp/appspec.yml .
      - cp -r WebApp/scripts .

artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/**/*
    - static/**/*
    - '**/*'
  base-directory: '.'
  discard-paths: no